### ISSUE TITLE
Add support to output the pre and post values that are graphed for treatment and comparison groups

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/LongitudinalDifferenceInDifferencesPy#3]
When trying to understand the percentage improvement of a treatment, getting the outputs of the pre and post values of treatment and comparison would be super helpful. Bigger plus would be to have the treatment % impact outputted along with the set of outputs already printed to the CMD today.

**Comment by csbuja** [comment]
Totally agree. These are super useful numbers to show when showing what your program has done.

Let’s think about how we’ll add this functionality to didDesigner. Feel free to submit a draft PR with the functions you’ll add and what they’ll do.

**Comment by jlbuja** [comment]
@HenokAddis Working on a draft now should be finished tonight.

**Comment by jlbuja** [comment]
https://github.com/microsoft/LongitudinalDifferenceInDifferencesPy/pull/8

**Comment by csbuja** [comment]
merged the changes! Thanks @jlbuja!
