### ISSUE TITLE
No screenshot for statistical estimates

### ISSUE THREAD

**Issue by jlbuja** [microsoft/LongitudinalDifferenceInDifferencesPy#5]
![Screen Shot 2019-07-05 at 5 59 57 PM](https://user-images.githubusercontent.com/52586547/60749442-e92fcc00-9f4e-11e9-9d57-974dae9c7e27.png)

**Comment by csbuja** [comment]
Cool. TY for the screenshot. I'll add it to the Wiki page: https://github.com/microsoft/LongitudinalDifferenceInDifferencesPy/wiki/Statistical-Estimates

**Comment by csbuja** [comment]
done!

**Comment by csbuja** [comment]
@jlbuja
